import './scripts/isPrime.js'
import './scripts/factorial.js'
import './scripts/fib.js'
import './scripts/isSorted.js'
import './scripts/reversePalindrome.js'
import './scripts/missing.js'
import './scripts/indexOf.js'
import './scripts/isBalanced.js'